version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: