version: '3.8'

services:
  api:
    build: .
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_DB}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_ACCESS_EXPIRE_IN=${JWT_ACCESS_EXPIRE_IN}
      - JWT_REFRESH_EXPIRE_IN=${JWT_REFRESH_EXPIRE_IN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PHONE=${ADMIN_PHONE}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ROLE_ADMIN_NAME=${ROLE_ADMIN_NAME}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM=${SENDGRID_FROM}
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: