export enum RESOURCES {
  USER = 'USER',
  ROLE = 'ROLE',
  ACTIVITY_LOG = 'ACTIVITY_LOG',
  PROFILE = 'PROFILE',
  STATUS = 'STATUS',
  ADDRESS = 'ADDRESS',
  HOUSEHOLD = 'HOUSEHOLD',
  MEMBERSHIP = 'MEMBERSHIP',
  RELATIONSHIP_TYPE = 'RELATIONSHIP_TYPE',
  RELATIONSHIP = 'RELATIONSHIP',
}
